export const pageStyles = {
  root: "flex flex-col gap-6 w-full max-w-full bg-white/85 dark:bg-slate-900/85 backdrop-blur-xs p-4 sm:p-6 text-slate-900 dark:text-slate-100 animate-fadeIn",
  headerWrapper: "flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-slate-200/60 dark:border-slate-800/60",
  headerSpace: "space-y-1.5 min-w-0 flex-1",
  nav: "flex items-center gap-1.5 text-xs font-medium text-slate-500 dark:text-slate-400 mb-1 flex-wrap",
  homeIcon: "inline-flex items-center justify-center p-1 rounded-md text-slate-400 hover:text-blue-600 dark:hover:text-blue-400 hover:bg-slate-100 dark:hover:bg-slate-800/80 transition-all",
  breadcrumbItem: "flex items-center gap-1.5 text-xs font-medium text-slate-500 dark:text-slate-400",
  breadcrumbLink: "hover:text-blue-600 dark:hover:text-blue-400 text-slate-500 dark:text-slate-400 transition-colors",
  breadcrumbActive: "text-slate-800 dark:text-slate-200 font-semibold tracking-tight",
  separator: "w-3.5 h-3.5 text-slate-300 dark:text-slate-600 shrink-0",
  titleWrapper: "space-y-1",
  title: "text-2xl sm:text-3xl font-extrabold tracking-tight text-slate-900 dark:text-slate-50 font-display",
  subtitle: "text-sm sm:text-base text-slate-500 dark:text-slate-400 max-w-3xl leading-relaxed font-normal",
  actionsWrapper: "flex flex-wrap items-center gap-2.5 shrink-0 w-full sm:w-auto mt-2 sm:mt-0",
  searchInputWrapper: "relative group w-full sm:w-72 min-w-[240px]",
  searchIcon: "absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400 group-focus-within:text-blue-600 dark:group-focus-within:text-blue-400 transition-colors pointer-events-none",
  searchInput: "w-full pl-9 pr-8 py-2 text-sm bg-white dark:bg-slate-800/90 border border-slate-200 dark:border-slate-700/80 rounded-xl text-slate-900 dark:text-slate-100 placeholder-slate-400 focus:outline-hidden focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 hover:border-slate-300 dark:hover:border-slate-600 transition-all shadow-2xs h-10",
  searchClearBtn: "absolute right-2.5 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 p-0.5 rounded-full hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors",
  contentContainer: "w-full flex flex-col",
  loaderWrapper: "flex items-center justify-center py-20 min-h-[300px]",
  spinner: "h-9 w-9 animate-spin rounded-full border-3 border-blue-200 dark:border-blue-900 border-t-blue-600 dark:border-t-blue-400",
};
